### ISSUE TITLE
Ошибка импорта

### ISSUE THREAD

**Issue by martinjack** [jack-theripper/yandex#2]
Не могу установить связь с библиотекой. Fatal error: Class 'Mackey\Yandex\Client' not found in
Код вызова:
use \Curl\Curl;
$curl = new Curl();
$client = new Mackey\Yandex\Client(ACCESS_TOKEN);

**Comment by jack-theripper** [comment]
Перед вызовом, тебе нужно подключить нужные файлы 

``` php
require_once '<путь до>/Mackey/Yandex/Client.php';
```

или проще определить автозагрузчик, и правильный путь до файлов

``` php
spl_autoload_register(function ($class) {
    $class = __DIR__.DIRECTORY_SEPARATOR.$class.'.php';

    if (is_file($class))
    {
        require_once $class;
    }
});
```

**Comment by martinjack** [comment]
Теперь появилась ошибка Fatal error: Class 'Mackey\Yandex\Request'. 
Есть возможность может собрать библиотеку через composer? WebDAV библиотека собрана через composer работает нормально.

**Comment by martinjack** [comment]
Если подгрузить класс через require_once, то видит его. Но уже в самом файле Request 
ошибка Parse error: syntax error, unexpected '[' in /www/include/yadisk/Mackey/Yandex/Request.php on line 30

**Comment by martinjack** [comment]
Всё работает. Оказалось проблема в версии php.

**Comment by jack-theripper** [comment]
Просто определи в коде автозагрузчик, композитор будет - когда-нибудь, когда руки дойдут оформлю. Но ты можешь помочь если есть желание. PHP версия 5.5 или выше
