### ISSUE TITLE
Docviewer для  публичных доков не работает

### ISSUE THREAD

**Issue by Snegirekk** [jack-theripper/yandex#21]
```
$public = $disk->getPublishResource($publicKey);
$publicViewer = $public->docviewer;
```
Возвращает неверную ссылку вьюера.

В классе Arhitector\Yandex\Disk\Resource\Opened 400-403 строки - то ли я дурак, то ли $this->get('path', '/') никогда не возвращает "/". И, значит, эта проверка всегда приделывает ':/'.ltrim($this->get('path'), '/ ') после публичного ключа и перед именем файла. И, в итоге, ссылка неправильная и не работает.

**Comment by jack-theripper** [comment]
Действительно не работает, но так было не всегда ранее path возвращал путь до публичной папки, в которой находится непосредственно файл. Сейчас исправлено, спасибо за помощь
