### ISSUE TITLE
Пример по работе с событием progress

### ISSUE THREAD

**Issue by campusboy87** [jack-theripper/yandex#24]
Дмитрий, здравствуйте. Большое спасибо за проделанную работу!

Вы не могли бы привести пример, как работать с событием progress? Сейчас я принимаю от пользователя файл, загружаю на хостинг - прогресс бар на загрузку реализовать смог. Но теперь этот файл нужно загрузить на Я.Диск и удалить соответственно с хостинга. Так как у меня 2 операции (2 загрузки: на хостинг + затем на Я.Диск), то этот прогресс бар отображает "нечестный" процент. Я хочу переделать на два прогресс бара. Для загрузки на сервер + на загрузку в Я.Диск. И моих знаний не хватает, чтобы это провернуть на основе Вашей библиотеки. Буду рад примеру или хотя бы совету. Может быть я не верно выбрал даже алгоритм работы.

**Comment by jack-theripper** [comment]
@campusboy87 

Здравствуйте. Библиотека поддерживает прогресс на выгрузку, значение вычисляется по факту **чтения** файла, расположенного на хостинге. Вы можете складывать значения ваших процессов и делить на 2

```php
$resource = $disk->getResource('путь/до/файла/наядиске.zip');
$resource->addListener('progress', function ($event, $percent) {
	static $latest = 0;
	// т.к. файл по сети скорее всего у вас будет передаваться частями по 16кб процент на большом файле может быть не презентативным
	if ($percent - $latest >= 5 || ! $latest || $percent == 100) {
		$latest = $percent; // $percent выводите пользователю
		show_percent($percent); // значение это float
		
		printf('процент %f%%', $percent); 
	}
});

$resource->upload('ваш файл на хотинге или fopen или new Stream', true);

var_dump($resource->toArray());
```
Доставляете значение до пользователя вашим способом 
```php
function show_percent($percent) {
	$show_percent = 100; // тут может быть результат вашего 1 прогресса
	// ...
	$show_percent += $percent;
	echo json_encode(['percent' => ($show_percent ?: 1) / 2]);	
}
```

**Comment by campusboy87** [comment]
Большое спасибо за ответ!
