### ISSUE TITLE
Куда вводить токен?

### ISSUE THREAD

**Issue by AquaG-zz-en** [jack-theripper/yandex#5]
Что-то непонятное в описании. Вот я получил токен и куда его вводить? В папке DataContainer в какой-то файл? Или в папке Yandex В какой-то файл? Или куда? чтобы я допустим увидел, что содержится в моем яндекс диске, куда вводить?

**Comment by jack-theripper** [comment]
Создаете у себя любой другой файл, например "index.php" - в этом файле вы будете работать.
Перед началом работы, тебе нужно подключить нужные файлы библиотеки в начале файла "index.php" любыми способами, руками/не руками, автозагрузчиком или установить через composer.

``` php
require_once '<путь до>/Mackey/Yandex/Client.php'; // подключить и другие файлы
```

Создать объект, как показано в документации и вместо "OAuth-токен" ввести свой токен, который заранее получил

``` php
 $disk = new Mackey\Yandex\Disk('OAuth-токен');

var_dump($disk ->getContents());
```

**Comment by AquaG-zz-en** [comment]
что-то я не понял. я должен все файлы в архиве вручную подключить к моему файлу? их там сколько? штук 20-30. каждый так прописывать? 
и ошибки какие-то появляются.  Fatal error: Class 'Curl\Curl' not found in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test\Yandex\Request.php on line 21

**Comment by jack-theripper** [comment]
ты не внимательно читаешь =) удобнее всего воспользуйся композитором

```
$ composer require arhitector/yandex dev-master
```

**Comment by AquaG-zz-en** [comment]
ввел это в командную строку, но ничего не получилось

> $ composer require arhitector/yandex dev-master
> "$" не является внутренней или внешней
> командой, исполняемой программой или пакетным файлом.

вот такой код я написал,  но не работает ничего
<?
require_once 'DataContainer/ContainerTrait.php'; 
require_once 'DataContainer/Container.php'; 
require_once 'Yandex/Client.php'; // подключить и другие файлы
require_once 'Yandex/Disk.php'; // подключить и другие файлы
require_once 'Yandex/CiperTrait.php'; // подключить и другие файлы
require_once 'Yandex/Request.php'; // подключить и другие файлы

 $disk = new Mackey\Yandex\Disk('');

var_dump($disk ->getContents());
?>

**Comment by jack-theripper** [comment]
Я может чего не понимаю, в Windows команда вводиться без "$", естественно композитор должен быть установлен.

Тогда тебе нужно самому установить все зависимости, сам SDK и php-curl-class. Положить это все, например в папку vendor (чтобы было vendor/Mackey/Yandex и т.д. и vendor/Curl/Curl.php) и воспользоваться автозагрузчиком

``` php
// например, таким
spl_autoload_register(function ($class) {
    $class = __DIR__.'/vendor/'.$class.'.php';

    if (is_file($class))
    {
        require_once $class;
    }
});
```

**Comment by AquaG-zz-en** [comment]
Понятия не имею что такое композитор, в любом случае он у меня даже не ставится. Что-то написано и нет кнопки продолжить. А пересобрать php я не могу потому что я его с сайта скачал. Что было, то и скачал.

Some settings on your machine make Composer unable to work properly.
Make sure that you fix the issues listed below and run this script again:

The openssl extension is missing, which means that secure HTTPS transfers are impossible.
If possible you should enable it or recompile php with --with-openssl

Какой SDK откуда скачиват куда я тоже не понял.
Мне в общем чтобы на EasyPHP-DevServer-14.1VC11 это работало что надо скачать?

**Comment by jack-theripper** [comment]
SDK это и есть вот этот репозиторий, это то что ты хочешь установить. Перечитай еще раз описание этого репозитория (раздел требования), ты взял исходники только этого репозитория, поэтому у тебя фатальная ошибка ибо не хватает еще одной другой библиотеки, в описании указано вот так "либа с репозитория php-curl-class", посмотри мои репозитории - там она есть, скачай и тоже подключи в свой проект.
Могу лишь посоветовать в качестве бонуса подучить документацию по php. Надеюсь у тебя всё получиться и ты сможешь разобраться =)
