### ISSUE TITLE
Невозможно удалить локальный файл после загрузки

### ISSUE THREAD

**Issue by savolgin** [jack-theripper/yandex#50]
При попытке удалить файл локально после его загрузки

````php
...
$resource->upload($fileName);
...
unlink($fileName);
````

В логах выводится ошибка о том что файл заблокирован
`ErrorException [ Warning ]: unlink(...): Text file busy`

В итоге файл не удаляется.

php 7.1
версия пакета 2.0.1

**Comment by jack-theripper** [comment]
Библиотека не блокирует файлы и не мешает удалению. Ошибка относится к операционной системе, специфичный случай где файл считается сегментом к процессу. 

Сомневаюсь что тебе это поможет - смотри описание в Readme к [патчу](https://github.com/jack-theripper/yandex/commit/8ebf7bf1c312e667d05f00d425ba29997d60203d), ты можешь принудительно вызвать $stream->close() в обработчике `uploaded`

**Comment by savolgin** [comment]
Да, т.к. эти исправления в мастере а у меня php7.1 воспользоваться этим не получится. Спасибо за быстрый ответ.

**Comment by savolgin** [comment]
В итоге создал наследника класса \Arhitector\Yandex\Disk\Resource\Closed

скопировал в него метод upload  и добавил в него закрытие стрима.
