### ISSUE TITLE
PHP 8.2 deprecation

### ISSUE THREAD

**Issue by reimax** [jack-theripper/yandex#54]
Добрый день!
PHP 8.2
Получил такую ошибку:
`You cannot use "Http\Message\MessageFactory\DiactorosMessageFactory" as the "php-http/message-factory" package is not installed. Try running "composer require php-http/message-factory". Note that this package is deprecated, use "psr/http-factory" instead`

**Comment by jack-theripper** [comment]
Добрый, выполните команду 
` composer require php-http/message-factory `

**Comment by reimax** [comment]
да, сделал это, все заработало. но этот репозитарий deprecated и редонли стал
