### ISSUE TITLE
Так задумано, что Closed можно удалить, а Open - нет?

### ISSUE THREAD

**Issue by victor78** [jack-theripper/yandex#58]
Хочу получить ресурс по его ключу, а затем удалить. Но в объекте нет такого метода. Так и задумано? API ЯД не дает такой возможности?
Или, если дает, то может стоит переместить метод в AbstractResource?

**Comment by jack-theripper** [comment]
Доступ к опубликованному ресурсу можно закрыть с OAuth-токеном владельца этого ресурса.

**Comment by victor78** [comment]
@jack-theripper 
Сейчас по ключу ресурса можно получить ресурс только через getPublishResource, и он возвращает Closed.
И у Closed нет метода удаления.
Мне кажется, ресурс корректнее получать по его ключу (скорее всего на стороне яндекса это первичный ключ, по которому поиск происходит быстрее).
Но в таком случае нет возможности использовать метод delete.

**Comment by jack-theripper** [comment]
Нет https://github.com/jack-theripper/yandex/blob/49f51b32f76cbfd123bb9fad7fdc63619121a884/src/Disk.php#L310

> Доступ к опубликованному ресурсу можно закрыть с OAuth-токеном владельца этого ресурса.

**Comment by victor78** [comment]
@jack-theripper 
Верно, извините. Возвращается Opened, и у него нет метода удаления.
