### ISSUE TITLE
Уточнение по лицензии

### ISSUE THREAD

**Issue by loginwashere** [jack-theripper/yandex#8]
Как я понимаю лицензия у библиотеки MIT (судя по composer.json).
Но все же хотелось бы уточнить лицензию.

Как я понимаю желательно добавить файл с лицензией в репозиторий.
https://help.github.com/articles/open-source-licensing/ - на всякий случай сслыка на помощь по лицензиям

**Comment by jack-theripper** [comment]
Да все правильно, MIT.
Добавили, спасибо
